version: "3.7"

services:
  server:
    image: tuktukwan-api
    build: .
    restart: always
    networks:
      - api
    environment:
      - NODE_ENV=development
    env_file: 
      - .env.local
      - .env
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_started
      session_storage:
        condition: service_started

  session_storage:
    image: redis:7.2.4
    networks:
      - api
    ports:
      - "6379:6379"

  database:
    image: postgres:14.3
    networks: 
      - api
    ports:
      - "5432:5432"
    env_file: 
      - .env.local
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local

networks:
  api:
    external: false