name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} --build-arg GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }} --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }} --build-arg MICROSOFT_CLIENT_ID=${{ secrets.MICROSOFT_CLIENT_ID }} --build-arg MICROSOFT_CLIENT_SECRET=${{ secrets.MICROSOFT_CLIENT_SECRET }} --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} --build-arg SERVER_KEY=${{ secrets.SERVER_KEY }} --build-arg HOST_URL=${{ secrets.HOST_URL }} -t $DOCKER_IMAGE .
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

      - name: Docker Hub login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}

      - name: Deploy to Swarm
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: docker stack deploy -c ${{ secrets.YAML_PATH }} ${{ secrets.SERVICE_NAME }}
